two:
  name: TwoName
  desc: TwoDesc
four:
  name: FourName
  desc: FourDesc

test:
  limitSizeMap:
    baidu: 1024
    sogou: 90
    hauwei: 4096
    qq: 1024

test-list:
  limitSizeList[0]: "baidu: 1024"
  limitSizeList[1]: "sogou: 90"
  limitSizeList[2]: "hauwei: 4096"
  limitSizeList[3]: "qq: 1024"
server:
  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:mysql://192.168.2.3:3306/sup_midserver_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Sh3m%oMk
    driverClassName: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-active: 15
    max-lifetime: 86430000
    log-abandoned: true
    remove-abandoned: true
    remove-abandoned-timeout: 60
    initialize: false
    sqlScriptEncoding: UTF-8
